# Generated by Django 3.2.12 on 2025-05-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('teaspoons', 'tsp'), ('cups', 'cups'), ('grams', 'grams')], default='grams', max_length=20),
        ),
    ]
