# Generated by Django 3.2.12 on 2025-04-21 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipedb', '0002_auto_20250421_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
