# Generated by Django 3.2.12 on 2025-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipedb', '0002_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('liters', 'L'), ('grams', 'grams'), ('milliliters', 'mL'), ('cups', 'cups'), ('teaspoons', 'tsp')], default='grams', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('liters', 'L'), ('grams', 'grams'), ('milliliters', 'mL'), ('cups', 'cups'), ('teaspoons', 'tsp')], default='grams', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(choices=[('liters', 'L'), ('grams', 'grams'), ('milliliters', 'mL'), ('cups', 'cups'), ('teaspoons', 'tsp')], max_length=20),
        ),
    ]
