# Generated by Django 3.2.12 on 2025-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipedb', '0003_auto_20250505_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('grams', 'grams'), ('teaspoons', 'tsp'), ('liters', 'L'), ('milliliters', 'mL'), ('cups', 'cups')], default='grams', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('grams', 'grams'), ('teaspoons', 'tsp'), ('liters', 'L'), ('milliliters', 'mL'), ('cups', 'cups')], default='grams', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(choices=[('grams', 'grams'), ('teaspoons', 'tsp'), ('liters', 'L'), ('milliliters', 'mL'), ('cups', 'cups')], default='grams', max_length=20),
        ),
    ]
