# Generated by Django 3.2.12 on 2025-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipedb', '0004_auto_20250505_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.PositiveIntegerField(help_text='per 100g'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('cups', 'cups'), ('liters', 'L'), ('grams', 'grams'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('ml', 'mL')], default='grams', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('cups', 'cups'), ('liters', 'L'), ('grams', 'grams'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('ml', 'mL')], default='grams', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(choices=[('cups', 'cups'), ('liters', 'L'), ('grams', 'grams'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('ml', 'mL')], default='grams', max_length=20),
        ),
    ]
