# Generated by Django 3.2.12 on 2025-04-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipedb', '0004_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
