# Generated by Django 3.2.12 on 2025-04-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipedb', '0005_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipedb.RecipeIngredient', to='recipedb.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipedb.recipe'),
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('list_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipedb.list')),
                ('ingredients', models.ManyToManyField(related_name='in_shopping_list', to='recipedb.Ingredient')),
            ],
            bases=('recipedb.list',),
        ),
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('list_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipedb.list')),
                ('recipes', models.ManyToManyField(related_name='in_recipe_lists', to='recipedb.Recipe')),
            ],
            bases=('recipedb.list',),
        ),
    ]
