# Generated by Django 3.2.12 on 2025-05-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipedb', '0005_auto_20250505_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('cups', 'cups'), ('tbsp', 'tbsp'), ('grams', 'grams'), ('ml', 'mL'), ('tsp', 'tsp'), ('liters', 'L')], default='grams', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('cups', 'cups'), ('tbsp', 'tbsp'), ('grams', 'grams'), ('ml', 'mL'), ('tsp', 'tsp'), ('liters', 'L')], default='grams', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(choices=[('cups', 'cups'), ('tbsp', 'tbsp'), ('grams', 'grams'), ('ml', 'mL'), ('tsp', 'tsp'), ('liters', 'L')], default='grams', max_length=20),
        ),
    ]
