# Generated by Django 5.2 on 2025-04-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipedb", "0006_auto_20250429_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="substitutes",
            field=models.ManyToManyField(blank=True, to="recipedb.ingredient"),
        ),
    ]
