# Generated by Django 5.2 on 2025-04-29 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipedb", "0007_alter_ingredient_substitutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_recipes",
                    models.ManyToManyField(
                        blank=True, related_name="liked_by", to="recipedb.recipe"
                    ),
                ),
                (
                    "restricted_ingredients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="restricted_by",
                        to="recipedb.ingredient",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
