# Generated by Django 3.2.12 on 2025-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipedb', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='substitutes',
            field=models.ManyToManyField(blank=True, related_name='_recipedb_ingredient_substitutes_+', to='recipedb.Ingredient'),
        ),
    ]
